---
title: "data_manipulation"
author: "Fang Liu"
date: "9/28/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

Read in the .csv file
```{r}
litters <- read.csv(file = "./data/FAS_litters.csv")
names(litters)

#change all variables names to snake_case using janitor::clean_names()
litters_data = janitor::clean_names(litters)
names(litters_data)

#explore teh dataset
str(litters_data)
skimr::skim(litters_data)
view(litters_data)
```

Now, explore common functions in the deplyr package(i.e., select, filter)! 
```{r filter}
filter(litters_data, group == "Con7", gd0_weight < 23)
filter(litters_data, group == "Con7" & gd0_weight < 23) #two ways of using 'AND'
filter(litters_data, group %in% c("Con7", "Con8")) #find the observations where group is in Con7 or Con 8
```

```{r drop_null_values}
drop_na(litters_data) #this does not change the orginial data, but could be used in pipes
test <- drop_na(litters_data) #save the data as new dataset
drop_na(litters_data, gd0_weight)
```

Next, lets add or change columns! 
```{r mutate}
mutate(litters_data, weight_change = gd18_weight - gd0_weight)
mutate(litters_data, group = str_to_lower(group))
```

Let's rearrange the data.
```{r rearrange}
arrange(litters_data, gd_of_birth, gd0_weight)
```


## Pipes
```{r pipes}

#if we don't use pipes
litters_data_raw <- read.csv(file = "./data/FAS_litters.csv")
litters_clean_name = janitor::clean_names(litters_data_raw)
litters_select <- select(litters_clean_name, group, pups_survive)
litters_filtered <- filter(litters_select, group == "Con7")

#when we use pipes 
litters_df = read_csv("data/FAS_litters.csv") %>% 
  janitor::clean_names() %>%
  select(group, pups_survive) %>%
  filter(group == "Con7")


```




